/**
 * Product name generator.
 *
 * Each category has a pool of prefixes (adjectives/materials/brands),
 * product types, and optional suffixes. Names are generated by combining
 * these parts with varying patterns for natural variety.
 */

const TEMPLATES = {
  Electronics: {
    prefixes: [
      "Wireless", "Bluetooth", "Smart", "Digital", "Portable", "Professional",
      "Premium", "Ultra", "Mini", "Compact", "Advanced", "High-Speed",
      "Rechargeable", "Noise-Cancelling", "4K", "HD", "LED", "Solar-Powered",
      "Dual-Band", "Waterproof", "Foldable", "AI-Powered", "Touch-Screen",
    ],
    types: [
      "Mouse", "Keyboard", "Headphones", "Speaker", "Camera", "Monitor",
      "Tablet", "Charger", "USB Hub", "Cable", "Earbuds", "Microphone",
      "Webcam", "Router", "Hard Drive", "SSD", "Power Bank", "Drone",
      "Projector", "Printer", "Controller", "Adapter", "Soundbar",
      "Smartwatch", "Fitness Tracker", "Smart Display", "Streaming Device",
      "VR Headset", "E-Reader", "Dash Cam", "Action Camera", "Ring Light",
      "Surge Protector", "Smart Plug", "Wireless Charger", "Phone Stand",
    ],
    suffixes: [
      "Pro", "Max", "Elite", "Plus", "Lite", "Air", "XL", "SE", "Ultra",
      "V2", "Gen 3", "2024", "Edition", "Series X", "Mini",
    ],
  },

  Clothing: {
    prefixes: [
      "Cotton", "Linen", "Silk", "Organic", "Slim Fit", "Relaxed Fit",
      "Oversized", "Classic", "Vintage", "Modern", "Casual", "Formal",
      "Lightweight", "Heavyweight", "Stretch", "Breathable", "Quick-Dry",
      "Merino Wool", "Fleece-Lined", "Water-Resistant",
    ],
    types: [
      "T-Shirt", "Polo Shirt", "Button-Down Shirt", "Hoodie", "Sweatshirt",
      "Jacket", "Blazer", "Cardigan", "Vest", "Sweater", "Jeans", "Chinos",
      "Shorts", "Joggers", "Cargo Pants", "Dress Pants", "Skirt", "Dress",
      "Tank Top", "Henley", "Parka", "Raincoat", "Windbreaker", "Peacoat",
      "Flannel Shirt", "Turtleneck", "Leggings", "Romper",
    ],
    suffixes: [
      "Collection", "Essential", "Premium", "Heritage", "Classic",
      "Limited Edition", "Everyday", "Weekend",
    ],
  },

  Books: {
    prefixes: [
      "Complete", "Essential", "Ultimate", "Beginner's", "Advanced", "Modern",
      "Classic", "Illustrated", "Pocket", "Comprehensive", "Practical",
      "Introduction to", "Mastering", "The Art of", "Fundamentals of",
    ],
    types: [
      "Programming Guide", "Cookbook", "Novel", "History Book", "Science Book",
      "Business Strategy", "Self-Help Guide", "Art Book", "Biography",
      "Fantasy Novel", "Sci-Fi Novel", "Mystery Thriller", "Poetry Collection",
      "Travel Guide", "Philosophy Book", "Psychology Book", "Economics Book",
      "Fitness Guide", "Photography Guide", "Music Theory Book",
      "Mathematics Textbook", "Children's Book", "Graphic Novel",
      "Reference Manual", "Memoir", "Design Handbook", "Data Science Book",
    ],
    suffixes: [
      "2nd Edition", "3rd Edition", "Revised", "Deluxe Edition", "Hardcover",
      "Paperback", "Volume 1", "Volume 2", "Collector's Edition",
    ],
  },

  Home: {
    prefixes: [
      "Modern", "Rustic", "Minimalist", "Decorative", "Handcrafted",
      "Vintage", "Bohemian", "Scandinavian", "Industrial", "Luxury",
      "Eco-Friendly", "Adjustable", "Multi-Purpose", "Smart", "LED",
      "Battery-Powered", "Motion-Sensor",
    ],
    types: [
      "Throw Pillow", "Wall Clock", "Table Lamp", "Floor Lamp", "Area Rug",
      "Picture Frame", "Vase", "Candle Set", "Wall Art", "Mirror",
      "Curtains", "Blanket", "Cushion Cover", "Door Mat", "Storage Basket",
      "Shelf Organizer", "Plant Pot", "Coat Rack", "Umbrella Stand",
      "Diffuser", "Night Light", "Wind Chime", "Tapestry", "Bookend Set",
      "Trinket Tray", "Woven Basket", "Room Divider", "Ottoman",
    ],
    suffixes: [
      "Set", "Collection", "Pack", "Bundle", "Deluxe", "XL", "Mini",
    ],
  },

  Kitchen: {
    prefixes: [
      "Stainless Steel", "Cast Iron", "Non-Stick", "Ceramic", "Silicone",
      "Bamboo", "Glass", "Professional", "Digital", "Electric", "Manual",
      "Insulated", "Collapsible", "Dishwasher-Safe", "BPA-Free",
      "Double-Walled", "Premium",
    ],
    types: [
      "Knife Set", "Cutting Board", "Mixing Bowl", "Water Bottle",
      "Coffee Mug", "Frying Pan", "Saucepan", "Dutch Oven", "Baking Sheet",
      "Measuring Cups", "Spatula Set", "Whisk", "Tongs", "Peeler",
      "Can Opener", "Colander", "Storage Containers", "Spice Rack",
      "Blender", "Toaster", "Coffee Maker", "Kettle", "Air Fryer",
      "Food Processor", "Rice Cooker", "Slow Cooker", "Pressure Cooker",
      "Lunch Box", "Ice Cube Tray", "Wine Opener", "Cheese Grater",
      "Rolling Pin", "Oven Mitt", "Apron",
    ],
    suffixes: [
      "Pro", "XL", "Set", "Deluxe", "Mini", "Pack of 2", "Pack of 4",
    ],
  },

  Sports: {
    prefixes: [
      "Professional", "Adjustable", "Portable", "Heavy-Duty", "Lightweight",
      "Anti-Slip", "Quick-Dry", "High-Performance", "Competition",
      "Training", "Grip", "Shock-Absorbing", "Foldable", "Inflatable",
      "Premium", "Carbon Fiber",
    ],
    types: [
      "Yoga Mat", "Dumbbells", "Resistance Bands", "Jump Rope",
      "Foam Roller", "Pull-Up Bar", "Kettlebell", "Medicine Ball",
      "Exercise Ball", "Ab Roller", "Boxing Gloves", "Tennis Racket",
      "Basketball", "Soccer Ball", "Football", "Baseball Glove",
      "Cycling Jersey", "Swim Goggles", "Surfboard Fins", "Skateboard",
      "Badminton Set", "Table Tennis Paddle", "Cricket Bat", "Golf Clubs",
      "Workout Bench", "Battle Rope", "Agility Ladder", "Wrist Wraps",
      "Knee Sleeves", "Weight Belt",
    ],
    suffixes: [
      "Pro", "Elite", "Set", "Kit", "Pack", "XL", "Lite", "Tournament",
    ],
  },

  Accessories: {
    prefixes: [
      "Leather", "Canvas", "Genuine", "Handmade", "Designer", "Premium",
      "Vintage", "Sterling Silver", "Gold-Plated", "Titanium", "Stainless",
      "Minimalist", "Classic", "Luxe", "Crystal", "Beaded", "Woven",
    ],
    types: [
      "Wallet", "Belt", "Watch", "Sunglasses", "Backpack", "Tote Bag",
      "Crossbody Bag", "Clutch", "Bracelet", "Necklace", "Earrings",
      "Ring", "Scarf", "Tie", "Cufflinks", "Money Clip", "Keychain",
      "Phone Case", "Laptop Sleeve", "Passport Holder", "Card Holder",
      "Hat", "Cap", "Beanie", "Gloves", "Umbrella", "Hair Clip",
      "Headband", "Watch Band",
    ],
    suffixes: [
      "Collection", "Edition", "Set", "Premium", "Slim", "Classic",
    ],
  },

  Beauty: {
    prefixes: [
      "Organic", "Natural", "Hydrating", "Anti-Aging", "Vitamin C",
      "Retinol", "Hyaluronic", "Charcoal", "Rose", "Tea Tree",
      "Coconut Oil", "Aloe Vera", "SPF 50", "Gentle", "Deep Cleansing",
      "Sulfate-Free", "Paraben-Free", "Cruelty-Free", "Vegan",
    ],
    types: [
      "Face Cream", "Moisturizer", "Serum", "Cleanser", "Toner",
      "Sunscreen", "Face Mask", "Lip Balm", "Eye Cream", "Body Lotion",
      "Hand Cream", "Shampoo", "Conditioner", "Hair Oil", "Body Wash",
      "Perfume", "Cologne", "Deodorant", "Foundation", "Mascara",
      "Lipstick", "Concealer", "Makeup Brush Set", "Nail Polish",
      "Face Mist", "Exfoliator", "Hair Mask", "Beard Oil",
    ],
    suffixes: [
      "Pro", "Deluxe", "Travel Size", "Set", "Collection", "Duo",
      "Kit", "Bundle",
    ],
  },

  Furniture: {
    prefixes: [
      "Modern", "Rustic", "Industrial", "Mid-Century", "Scandinavian",
      "Adjustable", "Ergonomic", "Foldable", "Stackable", "Reclaimed Wood",
      "Solid Oak", "Bamboo", "Metal", "Glass-Top", "Upholstered",
      "Floating", "Wall-Mounted", "Convertible",
    ],
    types: [
      "Office Chair", "Desk", "Bookshelf", "Dining Table", "Coffee Table",
      "Side Table", "TV Stand", "Bed Frame", "Nightstand", "Dresser",
      "Wardrobe", "Bar Stool", "Recliner", "Sofa", "Loveseat",
      "Bench", "Console Table", "Filing Cabinet", "Standing Desk",
      "Gaming Chair", "Shoe Rack", "Storage Cabinet", "Wine Rack",
      "Plant Stand", "Step Stool", "Accent Chair", "Vanity Table",
    ],
    suffixes: [
      "Pro", "XL", "Compact", "Deluxe", "Set", "With Storage", "With Drawers",
    ],
  },

  Health: {
    prefixes: [
      "Organic", "Natural", "Sugar-Free", "Vegan", "Plant-Based",
      "High-Potency", "Time-Release", "Chewable", "Effervescent",
      "Cold-Pressed", "Raw", "Gluten-Free", "Non-GMO", "Premium",
    ],
    types: [
      "Multivitamin", "Protein Powder", "Fish Oil Capsules", "Probiotic",
      "Collagen Supplement", "Vitamin D", "Vitamin C", "Magnesium",
      "Zinc Tablets", "Iron Supplement", "Omega-3", "Melatonin",
      "Electrolyte Powder", "Green Superfood", "Turmeric Capsules",
      "Ashwagandha", "Apple Cider Vinegar Gummies", "Fiber Supplement",
      "Joint Support", "Eye Health Formula", "Digestive Enzymes",
      "Blood Pressure Monitor", "Pulse Oximeter", "Digital Thermometer",
      "Massage Gun", "Heating Pad", "Ice Pack",
    ],
    suffixes: [
      "60 Count", "90 Count", "120 Count", "30-Day Supply", "Pro",
      "Extra Strength", "Max", "Advanced Formula",
    ],
  },

  Office: {
    prefixes: [
      "Ergonomic", "Adjustable", "Wireless", "Portable", "Premium",
      "Heavy-Duty", "Self-Adhesive", "Magnetic", "Dry-Erase",
      "Noise-Cancelling", "USB-Powered", "Rechargeable", "Compact",
    ],
    types: [
      "Desk Organizer", "Monitor Stand", "Laptop Stand", "Desk Pad",
      "Whiteboard", "Corkboard", "Paper Shredder", "Label Maker",
      "Desk Fan", "Footrest", "Document Scanner", "Webcam Light",
      "Cable Management Kit", "Drawer Organizer", "File Folder Set",
      "Sticky Notes", "Desk Calendar", "Name Badge", "Business Card Holder",
      "Presentation Clicker", "Power Strip", "USB Desk Hub",
      "Monitor Arm", "Keyboard Tray", "Under-Desk Drawer",
    ],
    suffixes: [
      "Pro", "Deluxe", "Set", "Kit", "XL", "Mini", "V2",
    ],
  },

  Outdoor: {
    prefixes: [
      "Waterproof", "All-Weather", "Portable", "Collapsible", "Solar",
      "Insulated", "Heavy-Duty", "Ultralight", "Windproof", "UV-Protected",
      "Reflective", "Tactical", "Multi-Tool", "Compact", "Military-Grade",
    ],
    types: [
      "Tent", "Sleeping Bag", "Camping Stove", "Headlamp", "Flashlight",
      "Hiking Poles", "Hammock", "Cooler", "Water Filter", "Compass",
      "Binoculars", "Camp Chair", "Fire Starter Kit", "Dry Bag",
      "Carabiner Set", "Paracord Bracelet", "Camping Lantern", "Tarp",
      "Trail Map Holder", "Insect Repellent", "First Aid Kit",
      "Survival Kit", "Fishing Rod", "Tackle Box", "Life Jacket",
      "Kayak Paddle", "Climbing Harness", "Rain Poncho",
    ],
    suffixes: [
      "Pro", "XL", "Lite", "Kit", "Set", "Extreme", "Pack",
    ],
  },

  Grocery: {
    prefixes: [
      "Organic", "Natural", "Artisan", "Imported", "Fair Trade",
      "Sugar-Free", "Gluten-Free", "Whole Grain", "Cold-Pressed",
      "Raw", "Smoked", "Roasted", "Dried", "Fresh", "Premium",
    ],
    types: [
      "Coffee Beans", "Green Tea", "Olive Oil", "Honey", "Maple Syrup",
      "Dark Chocolate", "Trail Mix", "Granola", "Protein Bar",
      "Peanut Butter", "Almond Milk", "Coconut Water", "Hot Sauce",
      "Pasta", "Quinoa", "Chia Seeds", "Rice", "Oats", "Cereal",
      "Energy Drink", "Sparkling Water", "Beef Jerky", "Dried Mango",
      "Cashews", "Macadamia Nuts", "Matcha Powder", "Spice Set",
    ],
    suffixes: [
      "Pack of 6", "Pack of 12", "Family Size", "Bulk", "Sampler",
      "Variety Pack", "250g", "500g", "1kg",
    ],
  },

  Toys: {
    prefixes: [
      "Educational", "Interactive", "Remote Control", "Wooden", "Magnetic",
      "Building", "Creative", "Musical", "Stuffed", "Giant", "Mini",
      "Glow-in-the-Dark", "Solar-Powered", "Battery-Operated", "STEM",
    ],
    types: [
      "Building Blocks", "Puzzle", "Board Game", "Action Figure",
      "Doll", "Toy Car", "Train Set", "Robot", "Drone", "Plush Animal",
      "Art Kit", "Science Kit", "Card Game", "Play-Doh Set",
      "Marble Run", "Construction Set", "Telescope", "Microscope",
      "Magic Kit", "Kite", "Water Gun", "Nerf Blaster", "Yo-Yo",
      "Rubik's Cube", "Slime Kit", "Dinosaur Set", "Play Kitchen",
    ],
    suffixes: [
      "Set", "Deluxe", "XL", "Starter Kit", "Pro", "Junior", "Ages 3+",
      "Ages 6+", "Ages 8+",
    ],
  },

  Footwear: {
    prefixes: [
      "Comfortable", "Breathable", "Waterproof", "Lightweight", "Cushioned",
      "Arch-Support", "Memory Foam", "Slip-On", "Lace-Up", "Gore-Tex",
      "Genuine Leather", "Suede", "Canvas", "Mesh", "Steel-Toe",
      "Non-Slip", "Orthopedic",
    ],
    types: [
      "Running Shoes", "Walking Shoes", "Hiking Boots", "Sneakers",
      "Loafers", "Oxford Shoes", "Chelsea Boots", "Sandals", "Flip Flops",
      "Slippers", "Work Boots", "Basketball Shoes", "Tennis Shoes",
      "Dress Shoes", "Boat Shoes", "Moccasins", "Platform Shoes",
      "Ankle Boots", "Rain Boots", "Snow Boots", "Cross-Training Shoes",
      "Trail Runners", "Espadrilles", "Clogs",
    ],
    suffixes: [
      "Pro", "V2", "Lite", "Max", "Air", "Boost", "Ultra", "Classic",
    ],
  },

  Automotive: {
    prefixes: [
      "Universal", "Heavy-Duty", "Premium", "All-Season", "Custom-Fit",
      "Waterproof", "LED", "Anti-Slip", "Quick-Release", "Magnetic",
      "Professional", "Digital", "Cordless", "12V", "OEM",
    ],
    types: [
      "Car Cover", "Dash Cam", "Phone Mount", "Seat Covers", "Floor Mats",
      "Steering Wheel Cover", "Tire Pressure Gauge", "Jump Starter",
      "Battery Charger", "Car Vacuum", "Air Freshener", "Sun Shade",
      "Trunk Organizer", "License Plate Frame", "Roof Rack", "Bike Rack",
      "Cargo Net", "Emergency Kit", "Tool Kit", "Car Wash Kit",
      "Wiper Blades", "Headlight Bulbs", "OBD2 Scanner", "Blind Spot Mirror",
      "Gear Shift Knob", "Exhaust Tip",
    ],
    suffixes: [
      "Pro", "Set", "Kit", "Pack", "Universal Fit", "Deluxe", "XL",
    ],
  },

  Garden: {
    prefixes: [
      "Durable", "Rust-Proof", "Collapsible", "Solar-Powered", "Automatic",
      "Heavy-Duty", "Ergonomic", "Telescoping", "Self-Watering",
      "Weather-Resistant", "Decorative", "Raised", "Hanging", "Drip",
    ],
    types: [
      "Garden Hose", "Pruning Shears", "Trowel", "Rake", "Shovel",
      "Wheelbarrow", "Planter Box", "Compost Bin", "Bird Feeder",
      "Garden Gloves", "Watering Can", "Lawn Sprinkler", "Hedge Trimmer",
      "Leaf Blower", "Seed Starting Kit", "Grow Light", "Garden Kneeler",
      "Plant Labels", "Soil Test Kit", "Flower Pot", "Trellis",
      "Garden Bench", "Fence Panel", "Outdoor Thermometer", "Rain Gauge",
    ],
    suffixes: [
      "Set", "Kit", "Pro", "XL", "Deluxe", "Pack of 3", "Starter",
    ],
  },

  "Pet Supplies": {
    prefixes: [
      "Adjustable", "Durable", "Interactive", "Orthopedic", "Automatic",
      "Eco-Friendly", "Personalized", "Waterproof", "Reflective",
      "Stainless Steel", "BPA-Free", "Natural", "Organic", "Calming",
    ],
    types: [
      "Dog Bed", "Cat Tree", "Pet Carrier", "Dog Leash", "Cat Litter",
      "Food Bowl", "Water Fountain", "Dog Toy", "Cat Toy", "Pet Brush",
      "Nail Clipper", "Dog Harness", "Collar", "Pet Shampoo",
      "Training Treats", "Chew Bone", "Scratching Post", "Fish Tank Filter",
      "Bird Cage", "Hamster Wheel", "Pet GPS Tracker", "Dog Crate",
      "Flea Collar", "Pet Camera",
    ],
    suffixes: [
      "Small", "Medium", "Large", "XL", "Set", "Pro", "Deluxe",
    ],
  },

  Stationery: {
    prefixes: [
      "Premium", "Eco-Friendly", "Recycled", "Refillable", "Acid-Free",
      "Smooth", "Fine-Point", "Gel", "Felt-Tip", "Metallic", "Pastel",
      "Dual-Tip", "Erasable", "Archival", "Watercolor",
    ],
    types: [
      "Notebook", "Journal", "Planner", "Pen Set", "Marker Set",
      "Colored Pencils", "Highlighters", "Sticky Notes", "Tape Dispenser",
      "Stapler", "Paper Clips", "Binder Clips", "Pencil Case",
      "Sketchbook", "Calligraphy Set", "Washi Tape", "Stamps Set",
      "Envelope Set", "Index Cards", "Memo Pad", "Clipboard",
      "Letter Opener", "Fountain Pen", "Mechanical Pencil",
    ],
    suffixes: [
      "Set", "Pack of 12", "Pack of 24", "Collection", "Pro", "Mini",
      "A5", "A4",
    ],
  },

  Music: {
    prefixes: [
      "Professional", "Beginner", "Acoustic", "Electric", "Digital",
      "Portable", "Compact", "Studio", "Bluetooth", "Wireless",
      "Custom", "Vintage", "Semi-Hollow", "Full-Size", "Travel",
    ],
    types: [
      "Guitar", "Keyboard", "Drum Kit", "Microphone", "Headphones",
      "Amplifier", "Tuner", "Metronome", "Music Stand", "Guitar Strings",
      "Drum Sticks", "Capo", "Guitar Pick Set", "Audio Interface",
      "MIDI Controller", "Studio Monitor", "Pop Filter", "Boom Arm",
      "Cable Set", "Violin", "Ukulele", "Harmonica", "Saxophone Reed",
      "Piano Bench", "Sheet Music Binder", "Pedal Board",
    ],
    suffixes: [
      "Pro", "Studio", "Bundle", "Kit", "Set", "Essentials", "Starter Pack",
    ],
  },
};

/** Utility: pick a random element from an array. */
function pick(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}

/**
 * Generate a realistic product name for a given category.
 *
 * Uses varying patterns for natural diversity:
 * - 10% chance: just [Type]
 * - 50% chance: [Prefix] [Type]
 * - 25% chance: [Prefix] [Type] [Suffix]
 * - 15% chance: [Type] [Suffix]
 */
export function generateName(categoryName) {
  const template = TEMPLATES[categoryName];
  if (!template) return `${categoryName} Product`;

  const type = pick(template.types);
  const roll = Math.random();

  if (roll < 0.1) {
    return type;
  } else if (roll < 0.6) {
    return `${pick(template.prefixes)} ${type}`;
  } else if (roll < 0.85) {
    return `${pick(template.prefixes)} ${type} ${pick(template.suffixes)}`;
  } else {
    return `${type} ${pick(template.suffixes)}`;
  }
}
